import { Clock, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { TaskList } from "./task-list";

export default async function GoalsPage() {
  const session = await auth();
  
  const dbTasks = await prisma.task.findMany({
    where: { userId: session?.user?.id },
    orderBy: { createdAt: 'desc' },
    take: 20
  });

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-1">Tasks & Deadlines</h1>
          <p className="text-slate-500">Track your objectives generated by your AI Guardian.</p>
        </div>
        <Button className="bg-indigo-600 hover:bg-indigo-700 text-white">
          <Plus className="w-4 h-4 mr-2" />
          New Task
        </Button>
      </div>

      <div className="grid grid-cols-1 gap-6 mt-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="w-5 h-5 text-indigo-500" />
              Upcoming Deadlines
            </CardTitle>
          </CardHeader>
          <CardContent>
            <TaskList initialTasks={dbTasks.map(t => ({
              ...t,
              dueDate: t.dueDate ? t.dueDate.toISOString() : null,
              createdAt: t.createdAt.toISOString()
            }))} />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
